import {
  SignIn,
  SignInButton,
  SignOutButton,
  UserButton,
  useUser,
} from "@clerk/nextjs";
import Head from "next/head";
import { api } from "~/utils/api";
import { User } from "@clerk/nextjs/server";

export default function Home() {
  const user = useUser();

  console.log(User);
  const { data, isLoading } = api.post.getAll.useQuery();
  if (isLoading) {
    return <div>Loading...</div>;
  }
  if (!data) {
    return <div>No data</div>;
  }
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="fixed h-10 w-full bg-gradient-to-b from-[#589feb] to-[#76756e]">
        <div className="mr-4 flex justify-end pt-2">
          <UserButton afterSignOutUrl="/" />
        </div>
      </header>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#654395] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          {!user.isSignedIn && (
            <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
              for <span className="text-[hsl(280,100%,70%)]">Sacramento</span>{" "}
              only
            </h1>
          )}
          {!!user.isSignedIn && (
            <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
              built by{" "}
              {data?.map((post) => (
                <span key={post.id} className="text-[hsl(280,100%,70%)]">
                  {post.name && <span>{post.name}</span>}
                </span>
              ))}{" "}
              for sac
            </h1>
          )}
          <div>
            {!user.isSignedIn && (
              <h1 className="flex justify-center text-white"> Sign in </h1>
            )}
            {!!user.isSignedIn && (
              <h1 className="flex justify-center text-white"> Sign Out </h1>
            )}
            {!user.isSignedIn && (
              <SignInButton>
                <button className="flex w-20 justify-center rounded bg-white">
                  Sign In
                </button>
              </SignInButton>
            )}
            {!!user.isSignedIn && (
              <SignOutButton>
                <button className="w-20 rounded bg-white">Sign Out</button>
              </SignOutButton>
            )}
          </div>
          {!!user.isSignedIn && (
            <button className="rounded bg-slate-400">
              {data?.map((post) => (
                <div key={post.id} className="text-5xl">
                  {post.email && <span>{post.email}</span>}
                </div>
              ))}
            </button>
          )}
          {!!user.isSignedIn && (
            <div>
              {data?.map((post) => (
                <div key={post.id}>{post.name && <span>{post.name}</span>}</div>
              ))}
            </div>
          )}
          {!!user.isSignedIn && (
            <div>
              {data?.map((post) => (
                <div key={post.id}>
                  {post.content && <span>{post.content}</span>}
                </div>
              ))}
            </div>
          )}
          <SignIn path="/sign-in" routing="path" afterSignUpUrl="/sign-up" />
        </div>
      </main>
    </>
  );
}
